apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-crun
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,W2NyaW8ucnVudGltZV0KZGVmYXVsdF9ydW50aW1lID0gImNydW4iCltjcmlvLnJ1bnRpbWUucnVudGltZXMuY3J1bl0KcnVudGltZV9yb290ID0gIi9ydW4vY3J1biIK
        filesystem: root
        mode: 0644
        path: /etc/crio/crio.conf.d/50-crun
