apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-openshift-master-kargs
spec:
  kernelArguments:
    - systemd.log_level=debug
    - systemd.log_target=kmsg
    - printk.devkmsg=on
    - log_buf_len=1M
